### ISSUE TITLE
Identificador da transação

### ISSUE THREAD

**Issue by amadeujunior18** [levicosta201/gerencianet-pix-api#1]
Boa noite, primeiro quero agradecer sua ajuda e empenho em criar um package para Laravel, isso e incrível, parabéns.
Olhando sua documentação vi que vc só retoma 3 valores.

array:3 [▼
  "success" => "true"
  "barCode" => "CODIGO_DE_BARRAS_DO_QR_CODE"
  "qrCodeBase64" => "BASE_64_DO_QR_CODE"
] 

certo mais cadê o taxid ou outro valor para fazer consulta desse Pix? vi também que esse valor não e informado na geração do pix ate ai tubem pq pode deixar ele a opcional mais ele tem q ser informado para futura consulta. correto?

**Comment by levicosta201** [comment]
Muito obrigado, e excelente ponto, muito obrigado pela observação. Estarei corrigindo isso na próxima versão, caso desejar, sinta-se a vontade para abrir uma Pull Request/Issue  caso encontre novos Bugs. 😀

**Comment by levicosta201** [comment]
Bug corrigo na nova Release 0.1.30 Commit: [#99bb477e3be39f7d06972aa74ba3969f89e8a640](https://github.com/levicosta201/gerencianet-pix-api/commit/99bb477e3be39f7d06972aa74ba3969f89e8a640)
